---
- name: Install postgres sql server
  yum:
    name: "{{ db_server }}" 
    state: latest

- name: Check database initialization
  command: postgresql-check-db-dir  "{{ db_dir }}"
  register: check_db_output
  changed_when: check_db_output == 1
  ignore_errors: yes
                                            
- name: initilize postgres db if db is not initialized
  shell: postgresql-setup initdb
  when: check_db_output.rc != 0


- name: start and enable postgres
  service:
    name: "{{ db_server_name }}"
    enabled: yes
    state: started
