---
- name: install app server
  yum:
    name: "{{ payload }}"
    state: latest

- name: start app server
  service:
    name: "{{ payload }}"
    state: started
    enabled: yes

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  notify: restart "{{ payload }}"          

#- name: start app server
#  service:
#    name: "{{ payload }}"
#    state: restarted
#    enabled: yes
